// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://gue2wkmzc5fmnljlaabbdbla5m.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lub5egadcfdeve5w4r6plhdcfe",
    "aws_cognito_identity_pool_id": "eu-west-2:7036d3cb-efed-4905-a54e-e72fb7458f43",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_HtanvtmuD",
    "aws_user_pools_web_client_id": "23vc6p9ikchfnbtb6a1vcau28m",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;
